//=============================================================================
// Testbench: uart_tb (Upgraded)
// Description: Comprehensive self-checking testbench for uart_top module.
//
// Verification Strategy:
//   1. Directed Tests   - Known boundary values (0x00, 0xFF, 0x55, 0xAA)
//   2. Random Tests     - 20 random bytes generated by $random
//   3. Assertions       - Continuous property checks throughout simulation
//   4. Loopback         - TX output wired directly to RX input
//   5. Pass/Fail report - Printed to console at end of simulation
//
// FSM States Exercised:
//   TX: IDLE -> START -> DATA -> STOP -> IDLE
//   RX: IDLE -> START -> DATA -> STOP -> IDLE
//=============================================================================

`timescale 1ns/1ps

module uart_tb;

    //-------------------------------------------------------------------------
    // Parameters - scaled for fast simulation
    // Real system: CLK_FREQ=100MHz, BAUD=9600 → 10416 clocks/bit (too slow)
    // Sim system:  CLK_FREQ=10MHz,  BAUD=115200 → 86 clocks/bit (fast)
    //-------------------------------------------------------------------------
    localparam CLK_FREQ  = 10_000_000;
    localparam BAUD_RATE = 115200;
    localparam CLK_PERIOD = 100; // ns → 10 MHz

    //-------------------------------------------------------------------------
    // DUT signals
    //-------------------------------------------------------------------------
    reg        clk      = 0;
    reg        rst      = 1;

    // TX
    reg  [7:0] tx_data  = 0;
    reg        tx_start = 0;
    wire       tx_line;
    wire       tx_busy;

    // RX (loopback: tx_line → rx)
    wire [7:0] rx_data;
    wire       rx_data_valid;

    //-------------------------------------------------------------------------
    // Clock generation - 10 MHz
    //-------------------------------------------------------------------------
    always #(CLK_PERIOD/2) clk = ~clk;

    //-------------------------------------------------------------------------
    // DUT instantiation - uart_top (TX + RX)
    //-------------------------------------------------------------------------
    uart_top #(
        .CLK_FREQ  (CLK_FREQ),
        .BAUD_RATE (BAUD_RATE)
    ) dut (
        .clk          (clk),
        .rst          (rst),
        .tx_data      (tx_data),
        .tx_start     (tx_start),
        .tx           (tx_line),
        .tx_busy      (tx_busy),
        .rx           (tx_line),   // Loopback
        .rx_data      (rx_data),
        .rx_data_valid(rx_data_valid)
    );

    //-------------------------------------------------------------------------
    // Received data latch
    // Captures rx_data the moment rx_data_valid pulses
    // This prevents missing the 1-cycle valid pulse
    //-------------------------------------------------------------------------
    reg [7:0] received_data = 0;
    reg       got_data      = 0;

    always @(posedge clk) begin
        if (rst) begin
            got_data      <= 0;
            received_data <= 0;
        end else if (rx_data_valid) begin
            received_data <= rx_data;
            got_data      <= 1;
        end
    end

    //=========================================================================
    // ASSERTIONS - Continuous property checks
    // These fire automatically throughout simulation.
    // If violated, simulation prints an error and continues.
    //=========================================================================

    // Assertion 1: TX line must never be X or Z during normal operation
    always @(posedge clk) begin
        if (!rst) begin
            if (tx_line === 1'bx || tx_line === 1'bz) begin
                $display("ASSERTION FAIL [%0t]: tx_line is X/Z - unknown state on TX line!", $time);
            end
        end
    end

    // Assertion 2: tx_busy must deassert within reasonable time after tx_start
    // (max bits = 10 bits × CLKS_PER_BIT + margin)
    integer tx_start_time = 0;
    integer max_busy_cycles = (CLK_FREQ / BAUD_RATE) * 12;

    always @(posedge clk) begin
        if (tx_start) tx_start_time = $time;
        if (tx_busy && ($time - tx_start_time > max_busy_cycles * CLK_PERIOD)) begin
            $display("ASSERTION FAIL [%0t]: tx_busy held too long - possible TX hang!", $time);
        end
    end

    // Assertion 3: tx_start should not be raised while tx_busy is high
    always @(posedge clk) begin
        if (!rst && tx_start && tx_busy) begin
            $display("ASSERTION WARN [%0t]: tx_start raised while tx_busy HIGH - data may be lost!", $time);
        end
    end

    // Assertion 4: rx_data_valid must only pulse for exactly 1 clock cycle
    reg rx_valid_prev = 0;
    reg [2:0] valid_count = 0;

    always @(posedge clk) begin
        rx_valid_prev <= rx_data_valid;
        if (rx_data_valid && rx_valid_prev) begin
            $display("ASSERTION FAIL [%0t]: rx_data_valid held high for >1 cycle!", $time);
        end
    end

    //=========================================================================
    // Task: send_and_check
    // Sends one byte, waits for RX to latch it, compares, reports PASS/FAIL
    //=========================================================================
    integer pass_count = 0;
    integer fail_count = 0;

    task send_and_check;
    input [7:0] byte_val;
    input [63:0] test_name;
    reg   [63:0] test_name_r;
    begin
        test_name_r = test_name;
            // Clear latch
            @(posedge clk);
            got_data = 0;

            // Send byte
            tx_data  = byte_val;
            tx_start = 1;
            @(posedge clk);
            tx_start = 0;

            // Wait for RX to capture
            wait(got_data == 1);
            @(posedge clk);

            // Compare
            if (received_data == byte_val) begin
                $display("  PASS [%s]: Sent 0x%02h | Received 0x%02h",
                         test_name, byte_val, received_data);
                pass_count = pass_count + 1;
            end else begin
                $display("  FAIL [%s]: Sent 0x%02h | Received 0x%02h  <--- MISMATCH",
                         test_name, byte_val, received_data);
                fail_count = fail_count + 1;
            end

            // Inter-byte gap
            repeat(150) @(posedge clk);
        end
    endtask

    //=========================================================================
    // Main test sequence
    //=========================================================================
    integer i;
    reg [7:0] rand_byte;

    initial begin
        $dumpfile("uart_tb.vcd");
        $dumpvars(0, uart_tb);

        //---------------------------------------------------------------------
        // Reset sequence
        //---------------------------------------------------------------------
        rst = 1;
        repeat(10) @(posedge clk);
        rst = 0;
        repeat(5) @(posedge clk);

        $display("");
        $display("=========================================");
        $display("  UART Controller - Verification Suite  ");
        $display("  CLK: %0d MHz | BAUD: %0d", CLK_FREQ/1000000, BAUD_RATE);
        $display("=========================================");

        //---------------------------------------------------------------------
        // TEST GROUP 1: Directed boundary tests
        // These specific values stress the FSM:
        //   0x00 = all zeros  → maximum consecutive LOW bits (hardest for RX)
        //   0xFF = all ones   → maximum consecutive HIGH bits
        //   0x55 = 01010101   → alternating bits (max transitions)
        //   0xAA = 10101010   → alternating bits (opposite phase)
        //   0x41 = 'A'        → typical ASCII character
        //---------------------------------------------------------------------
        $display("");
        $display("--- Group 1: Directed Boundary Tests ---");
        send_and_check(8'h00, "ALL_ZERO");
        send_and_check(8'hFF, "ALL_ONES");
        send_and_check(8'h55, "ALT_0101");
        send_and_check(8'hAA, "ALT_1010");
        send_and_check(8'h41, "ASCII__A");

        //---------------------------------------------------------------------
        // TEST GROUP 2: Random tests
        // 20 random bytes generated by $random
        // Tests values the designer didn't think of
        //---------------------------------------------------------------------
        $display("");
        $display("--- Group 2: Random Tests (20 bytes) ---");
        for (i = 0; i < 20; i = i + 1) begin
            rand_byte = $random % 256;
            send_and_check(rand_byte, "  RANDOM");
        end

        //---------------------------------------------------------------------
        // TEST GROUP 3: ASCII string test - "HELLO"
        //---------------------------------------------------------------------
        $display("");
        $display("--- Group 3: ASCII String Test ---");
        send_and_check(8'h48, "       H");
        send_and_check(8'h45, "       E");
        send_and_check(8'h4C, "       L");
        send_and_check(8'h4C, "       L");
        send_and_check(8'h4F, "       O");

        //---------------------------------------------------------------------
        // Final report
        //---------------------------------------------------------------------
        $display("");
        $display("=========================================");
        $display("  RESULTS: %0d passed | %0d failed", pass_count, fail_count);
        if (fail_count == 0)
            $display("  STATUS : ALL TESTS PASSED");
        else
            $display("  STATUS : SOME TESTS FAILED - check above");
        $display("=========================================");
        $display("");

        $finish;
    end

    //-------------------------------------------------------------------------
    // Timeout watchdog - kills simulation if it hangs
    //-------------------------------------------------------------------------
    initial begin
        #100_000_000; // 100ms sim time limit
        $display("TIMEOUT: Simulation exceeded time limit - possible hang!");
        $finish;
    end

endmodule
